apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: circleguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: circleguard/file-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: uploads
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: file-service-svc
  namespace: circleguard
spec:
  type: NodePort
  selector:
    app: file-service
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
