apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: circleguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: circleguard/gateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          readinessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 12
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
          env:
            - name: SERVER_PORT
              value: "8087"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
  namespace: circleguard
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - port: 8087
      targetPort: 8087
      nodePort: 30087
