apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-service
  namespace: circleguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-service
  template:
    metadata:
      labels:
        app: form-service
    spec:
      containers:
        - name: form-service
          image: circleguard/form-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: circleguard-config
            - secretRef:
                name: circleguard-secrets
          env:
            - name: SERVER_PORT
              value: "8086"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-svc:5432/circleguard_form"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: form-service-svc
  namespace: circleguard
spec:
  type: NodePort
  selector:
    app: form-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086
